---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../manager/

configMapGenerator:
  - files:
      - ./config-defaults.yaml
    name: model-serving-config-defaults

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - params.yaml
