apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelmesh-controller
spec:
  template:
    spec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
      containers:
        - name: manager
          image: $(odh-modelmesh-controller)
          resources:
            limits:
              memory: 2Gi
          ports:
            - containerPort: 9443
              name: webhook
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: modelmesh-webhook-server-cert
              readOnly: true
      volumes:
        - name: modelmesh-webhook-server-cert
          secret:
            defaultMode: 420
            secretName: modelmesh-webhook-server-cert